post_install() {
  post_upgrade
  echo '==> You should define the path where your Age Of Empires CD-ROM is mounted by running:'
  echo '    $ echo "/path/where/the/cdrom/is/mounted" > "${XDG_CONFIG_HOME}/aoe/cdrom.conf"'
}

post_upgrade() {
  echo -n "Updating font cache... "
  fc-cache -f > /dev/null
  mkfontscale /usr/share/fonts/TTF
  mkfontdir /usr/share/fonts/TTF
  echo "done."
}

post_remove() {
  post_upgrade
}
